// <auto-generated />
namespace WebShop3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class manytoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281532039_many to Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
